// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using mobileBackendsoftFount.Data;

#nullable disable

namespace mobileBackendsoftFount.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250223054120_AddBenzeneTable")]
    partial class AddBenzeneTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("mobileBackendsoftFount.Models.Benzene", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<float>("priceOfLitre")
                        .HasColumnType("real");

                    b.Property<float>("priceOfSelling")
                        .HasColumnType("real");

                    b.Property<float>("rateOfEvaporation")
                        .HasColumnType("real");

                    b.Property<float>("rateOfTaxes")
                        .HasColumnType("real");

                    b.Property<float>("rateOfVats")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("Benzenes");
                });

            modelBuilder.Entity("mobileBackendsoftFount.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
